if (EXISTS "C:/Users/martin.LAPLAND/CLionProjects/programing-principles-and-practice/c14/e9/tests_tests-b12d07c.cmake")
    include("C:/Users/martin.LAPLAND/CLionProjects/programing-principles-and-practice/c14/e9/tests_tests-b12d07c.cmake")
else ()
    add_test(tests_NOT_BUILT-b12d07c tests_NOT_BUILT-b12d07c)
endif ()
